spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epid?currentSchema=epid
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
    #      data-locations: classpath:demo_data.sql
  liquibase:
      change-log: classpath:liquibase/db.changelog.yaml
      enabled: true
      default-schema: epid
  mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
  security:
    jwt:
      secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
      access: 3600000
      refresh: 2592000000
      # пишем эту аннотация для сваггера, что в респонсах излишние количество вариантов ответов с ошибками, которые мы в теории могли бы сконфигурировать и присвоить им номер ннапример еррор 500 и т.д. 
  springdoc:
    override-with-generic-response: false
