spring:
cache:
type: redis
cache-names: redis-cache
 data:
    redis:
    host: localhost
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/epid?currentSchema=epid
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: Ynpma2poZ2t1c2h2c2liaHhpdXNicGl1YmlndWZkYnNucGlnZmINCg
    access: 1
    refresh: 30
